version: '3.0'

expectations:
  population_size: 10000

actions:


# actions to plot TPP-STP size

  generate_cohort_diab:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2_diab --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_2_diab.csv
        
  assoc_diab:
    run: r:latest analysis/1-assoc_diab.R
    needs: [generate_cohort_diab]
    outputs:
      moderately_sensitive:
        model: output/models/diab-model.Rdata
